// ============================================================
// Cloudflare Pages Function — /config.js
//
// File ini menggantikan config.js statis.
// Kredensial Supabase dibaca dari Environment Variables
// yang di-set di Cloudflare Pages Dashboard, bukan dari kode.
//
// Set di: Pages > Settings > Environment Variables
//   SUPABASE_URL      = https://xxxx.supabase.co
//   SUPABASE_ANON_KEY = eyJhbGci...
// ============================================================

export async function onRequest(context) {
  const { env } = context;

  const supabaseUrl  = env.SUPABASE_URL  || '';
  const supabaseKey  = env.SUPABASE_ANON_KEY || '';

  // Jika env vars belum di-set, kembalikan script yang menampilkan error jelas
  if (!supabaseUrl || !supabaseKey) {
    const errorScript = `
(function() {
  document.addEventListener('DOMContentLoaded', function() {
    var overlay = document.getElementById('loadingOverlay');
    if (overlay) overlay.style.display = 'none';

    var banner = document.createElement('div');
    banner.style.cssText = [
      'position:fixed','inset:0','z-index:99999',
      'background:#1e293b','color:#f8fafc',
      'display:flex','flex-direction:column',
      'align-items:center','justify-content:center',
      'gap:16px','font-family:monospace','padding:32px',
      'text-align:center'
    ].join(';');
    banner.innerHTML = [
      '<div style="font-size:48px">⚙️</div>',
      '<h2 style="margin:0;font-size:20px;color:#f87171">Environment Variables Belum Di-set</h2>',
      '<p style="margin:0;max-width:480px;line-height:1.6;color:#94a3b8">',
        'Buka <strong>Cloudflare Pages → Settings → Environment Variables</strong> ',
        'dan tambahkan <code style="background:#334155;padding:2px 6px;border-radius:4px">SUPABASE_URL</code> ',
        'serta <code style="background:#334155;padding:2px 6px;border-radius:4px">SUPABASE_ANON_KEY</code>.',
      '</p>',
      '<a href="https://dash.cloudflare.com" target="_blank"',
         'style="background:#f97316;color:#fff;padding:10px 24px;border-radius:8px;text-decoration:none;font-weight:600">',
        'Buka Cloudflare Dashboard →',
      '</a>'
    ].join('');
    document.body.prepend(banner);
  });
})();
`;
    return new Response(errorScript, {
      status: 200,
      headers: {
        'Content-Type': 'application/javascript; charset=utf-8',
        'Cache-Control': 'no-store',
      },
    });
  }

  // Sanitasi nilai untuk mencegah JS injection
  const safeUrl = supabaseUrl.replace(/['"\\]/g, '');
  const safeKey = supabaseKey.replace(/['"\\]/g, '');

  const script = `
// Auto-generated by Cloudflare Pages Function — jangan edit manual
// Ubah nilai via: Pages > Settings > Environment Variables
window.SUPABASE_URL      = '${safeUrl}';
window.SUPABASE_ANON_KEY = '${safeKey}';
`;

  return new Response(script, {
    status: 200,
    headers: {
      'Content-Type': 'application/javascript; charset=utf-8',
      // Cache sebentar di edge — invalidate saat redeploy otomatis
      'Cache-Control': 'public, max-age=300, s-maxage=300',
    },
  });
}
